(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   '("f6665ce2f7f56c5ed5d91ed5e7f6acb66ce44d0ef4acfaa3a42c7cfe9e9a9013" "1704976a1797342a1b4ea7a75bdbb3be1569f4619134341bd5a4c1cfb16abad4" "835868dcd17131ba8b9619d14c67c127aa18b90a82438c8613586331129dda63" "0d01e1e300fcafa34ba35d5cf0a21b3b23bc4053d388e352ae6a901994597ab1" default))
 '(elfeed-feeds
   '("https://www.youtube.com/c/DistroTube"
     ("https://www.youtube.com/user/supergreatfriend" videos games)
     ("https://www.theguardian.com/theguardian/mainsection/topstories/rss" news tops)
     ("https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml" news tops)
     ("https://this-week-in-rust.org/rss.xml" programming rust)))
 '(package-selected-packages '(lsp-python-ms lsp-pyright))
 '(warning-suppress-log-types
   '((org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)))
 '(warning-suppress-types
   '((ein)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache)
     (org-element-cache))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(doom-modeline-buffer-modified ((t (:foreground "orange"))))
 '(markdown-header-face-1 ((t (:height 1.25 :weight extra-bold :inherit markdown-header-face))))
 '(markdown-header-face-2 ((t (:height 1.15 :weight bold :inherit markdown-header-face))))
 '(markdown-header-face-3 ((t (:height 1.08 :weight bold :inherit markdown-header-face))))
 '(markdown-header-face-4 ((t (:height 1.0 :weight bold :inherit markdown-header-face))))
 '(markdown-header-face-5 ((t (:height 0.9 :weight bold :inherit markdown-header-face))))
 '(markdown-header-face-6 ((t (:height 0.75 :weight extra-bold :inherit markdown-header-face))))
 '(org-document-title ((t (:height 1.2))))
 '(org-modern-statistics ((t (:inherit org-checkbox-statistics-todo))))
 '(outline-1 ((t (:weight extra-bold :height 1.25))))
 '(outline-2 ((t (:weight bold :height 1.15))))
 '(outline-3 ((t (:weight bold :height 1.12))))
 '(outline-4 ((t (:weight semi-bold :height 1.09))))
 '(outline-5 ((t (:weight semi-bold :height 1.06))))
 '(outline-6 ((t (:weight semi-bold :height 1.03))))
 '(outline-8 ((t (:weight semi-bold))))
 '(outline-9 ((t (:weight semi-bold)))))
